
source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

workspace 'DependencyInjector'

target 'DependencyInjector' do

  pod 'SwiftLint', '0.47.1'
  pod 'Swinject', '~> 2.0'
  pod 'SwinjectAutoregistration', '~> 2.0'

  target 'DependencyInjectorTests' do
      
  end
end
